version: '3.8'

services:
  database:
    image: mysql
    restart: always
    container_name: commercedb
    environment:
      MYSQL_ROOT_PASSWORD: 1234!!
      MYSQL_DATABASE: commercedb
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    ports:
      - 3307:3306
    volumes:
      - com_data:/var/lib/mysql

  redis:
    image: redis
    restart: always
    container_name: commerceredis
    ports:
      - 6380:6379
    volumes:
      - redis_data:/data

volumes:
  com_data:
  redis_data: