version: '3.8'

services:
  database:
    image: mysql
    restart: always
    container_name: commercedb
    environment:
      MYSQL_ROOT_PASSWORD: 1234!!
      MYSQL_DATABASE: commercedb
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    ports:
      - 3307:3306
    volumes:
      - com_data:/var/lib/mysql

  redis:
    image: redis
    restart: always
    container_name: commerceredis
    ports:
      - 6380:6379
    volumes:
      - redis_data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper
    restart: always
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "write-order"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

volumes:
  com_data:
  redis_data: