server:
  port: 8081

spring:
  application:
    name: commerce

  datasource:
    url: jdbc:mysql://localhost:3307/commercedb
    username: kang
    password: 1234!!
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    data:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: chkangsc@gmail.com
    password: vkbtscxcpbneyljw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff